In [2]:
import numpy as np

In [47]:
# task 1
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# task 2
arr = np.zeros((3, 3), dtype=np.int_)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [73]:
# task 3
rng = np.random.default_rng()  
rng.integers(11, size=(5, 5))

array([[ 1,  1,  8,  5,  6],
       [ 6,  7,  0,  5,  1],
       [ 4, 10,  6,  0,  5],
       [ 1,  8, 10, 10,  6],
       [ 9,  4,  1,  5,  4]])

In [77]:
# task 4
rng = np.random.default_rng()  
rng.integers(2, size=(4, 4))


array([[1, 0, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 1]])

In [7]:
# task 5 
rng = np.random.default_rng()  
arr = rng.integers(11, size=(5))
brr = rng.integers(11, size=(5))
print(arr - brr)
print(arr + brr)
print(arr * brr)


[-7  1  1  4  2]
[ 9  1 19 12 14]
[ 8  0 90 32 48]


In [16]:
# task 6
arr = np.array([1, 3, 5, 7, 7, 9, 9])
brr = np.array([4, 5, 7, 2, 3, 6, 7])
arr @ brr

206

In [31]:
# task 7
rng = np.random.default_rng()  
arr = rng.integers(11, size=(2, 2))
brr = rng.integers(11, size=(2, 3))
res = np.dot(arr, brr)
res

array([[ 10,   7,   2],
       [102,  42,  24]])

In [17]:
# task 8
rng = np.random.default_rng()  
arr = rng.integers(11, size=(3, 3))
res = np.linalg.inv(arr)
res

array([[ 0.57142857, -0.14285714,  0.        ],
       [ 0.125     , -0.125     ,  0.125     ],
       [-0.35714286,  0.21428571, -0.        ]])

In [18]:
# task 9
rng = np.random.default_rng()  
arr = rng.integers(2, size=(4, 4))
arr.T

array([[1, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 1]])

In [19]:
# task 10
rng = np.random.default_rng()  
arr = rng.integers(11, size=(3, 4))
a =  rng.integers(11, size=(4))
arr * a

array([[ 0, 12, 32,  0],
       [ 0, 12, 12,  0],
       [ 0, 12, 40,  0]])

In [20]:
# task 11
rng = np.random.default_rng()  
arr = rng.integers(2, size=(2, 3))
a =  rng.integers(2, size=(3))
arr * a

array([[0, 1, 1],
       [0, 0, 0]])

In [28]:
# task 12
rng = np.random.default_rng()  
arr = rng.integers(11, size=(2, 2))
brr = rng.integers(11, size=(2, 2))
res = arr * brr
res

array([[24, 20],
       [ 7, 48]])

In [32]:
# task 13
rng = np.random.default_rng()  
arr = rng.integers(11, size=(2, 2))
brr = rng.integers(11, size=(2, 2))
arr @ brr

array([[58, 42],
       [59, 34]])

In [35]:
# task 14
rng = np.random.default_rng()  
arr = rng.integers(101, size=(5, 5))
arr.sum()

1351

In [36]:
# task 15
rng = np.random.default_rng()  
arr = rng.integers(11, size=(4, 4))
brr = rng.integers(11, size=(4, 4))
arr - brr

array([[-1,  1, -4,  1],
       [ 3,  5,  2,  2],
       [-5,  4, -9,  0],
       [-3,  4,  6,  2]])

In [68]:
# task 16
rng = np.random.default_rng()  
arr = rng.integers(2, size=(3, 3))
print(arr)
a = arr[0:, 0]
b = arr[0:, 1]
c = arr[0:, 2]
print(a)
print(b)
print(c)
new_a = a.reshape(-1, 1)
new_b = b.reshape(-1, 1)
new_c = c.reshape(-1, 1)
print(new_a.sum())
print(new_b.sum())
print(new_c.sum())

[[0 1 1]
 [0 1 0]
 [0 1 0]]
[0 0 0]
[1 1 1]
[1 0 0]
0
3
1


In [72]:
# task 17
rng = np.random.default_rng()  
arr = rng.integers(11, size=(3, 4))
print(arr)
brr = arr **2
brr

[[ 9  9  1  0]
 [ 5  5 10 10]
 [ 3  5  8  8]]


array([[ 81,  81,   1,   0],
       [ 25,  25, 100, 100],
       [  9,  25,  64,  64]])

In [76]:
# task 18
rng = np.random.default_rng()  
arr = rng.integers(51, size=(4))
print(arr)
brr = np.sqrt(arr).round(3)
brr

[ 7 37  4 17]


array([2.646, 6.083, 2.   , 4.123])